# Generated by Django 5.1.1 on 2024-10-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DT_VENCIMENTO', models.DateField()),
                ('DS_PERIODO_REFERENCIA', models.CharField(max_length=100)),
                ('DS_CONTA', models.CharField(max_length=255)),
                ('DT_PAGAMENTO', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
