# Generated by Django 5.1.1 on 2024-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='NU_VALOR',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='TP_CONTA',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
